### PR TITLE
Handling (or checking) possible failure in lease's KeepAlive.

### LINKED ISSUE #49: Get lease ttl and connection state for lock and keep-alive
I'm trying to understand how to get the lease TTL for a lock, and also ideally a callback on lease expiry. This happens for example during a network partition or an etcd failover.

Specifically I would want the following:
- Whether a lease has expired for a lock? (TTL = -1 on the keep-alive I believe)
- Whether the keep-alive connection has failed?

All help much appreciated!

### PR DESCRIPTION
**Pull request by sighingnow**
Resolves #49.

### CODE REVIEW

File: etcd/KeepAlive.hpp [hunk 1]
```diff
@@ -36,6 +52,13 @@ namespace etcd
      */
     void Cancel();
 
+    /**
+     * Check if the keep alive is still valid (invalid when there's an async exception).
```
Comment (pyssling) [inline etcd/KeepAlive.hpp:56]: @sighingnow I think here we also need to check if the last message from the server was with a timeout of -1 - I think this also indicates that the keep-alive is no longer valid. This can of course be checked with existing methods.

Comment (sighingnow) [reply etcd/KeepAlive.hpp:56]: Agree. Will commit such an enhancement later.

However please note that when constructing the `KeepAlive` object the `ttl` argument should be less than the TTL that used to grant the lease, and inside the implementation of `KeepAlive` the refresh the lease every `ttl - 1` seconds.

Thus generally this shouldn't be a problem, unless we encounter some problems on the server, or the lease is cancelled in an external thread.

Comment (pyssling) [reply etcd/KeepAlive.hpp:56]: Thanks!
